---
title: "EDS 221 Day 4 Tasks"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

Create two sequences, one called `weekdays` that contains days of the week ("Monday", "Tuesday", "Wednesday", etc.) and one called `transects` that contains the series of transect names "Transect A", "Transect B,"Transect C". Write a nested for loop that creates a matrix containing the following:

```{r}
weekdays <- c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
transects <- c("Transect A","Transect B","Transect C")


weekday_transects <- matrix(nrow= length(weekdays), ncol= length(transects))
```

```{r}
for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
  weekday_transects[i,j]= print(paste(weekdays[i],"-",transects[j]))
  }
}
weekday_transects
```

## **Part 2. Functions introduced**

```{r}
#task 2
force_calculation <- function(mass_kg, acceleration_movers2){
  force <- mass_kg * acceleration_movers2
  print(paste0(" The resulting force is ",force," Newtons."))
}
  
force_calculation(30,40)
```

```{r}
#task 3

fish_parms <- data.frame(sci_name= c("Chanos chanos", "Sphyraena barracuda","Caranx ignobilis"), common_name=c("Milkfish","Great barracida","Giant trevally"), a_est =c(0.0905,0.0181,0.0353), b_est=c(2.52,3.27,3.05))

fish_parms

fish_weight <- function(fish_name, tot_length){
  selected_fish_name <- filter(fish_parms, common_name == fish_name)
  (selected_fish_name$a_est) * (tot_length)^selected_fish_name$b_est
}

fish_weight(fish_name = "Milkfish", tot_length = 30)

fish_length_vector = seq(from=0, to= 100)

milkfish_weights <- fish_weight(fish_name = "Giant trevally", tot_length = fish_length_vector)
```

```{r}
#task 4
wave_power <- function(wave_height, wave_period){
  0.5 * (wave_height)^2 * wave_period
}
wave_period <- seq(from = 0 , to = 3, by = 0.2)
wave_power(8, wave_period)
```

```{r}
#task 5
wave_power_shallow <-function(wave_height, wave_period){
  if (wave_height > 12){
    message("Used the deep wave power equation")
    0.5 * (wave_height)^2 * wave_period
  }else if (wave_height <= 12){
    message("Used the shallow wave power equation")
    0.81 * (wave_height)^2 * wave_period
  }
   
}
wave_power_shallow(1, 1)
```
